### ISSUE TITLE
TR for 1.12 TODO list

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#1084]
- [x] Rewrite cables + fix power issues

- [ ] Remove MCMP from RebornCore

- [ ] Remove core mod

- [ ] Abstract Recipes

- [ ] Fix bugs I guess

Some things can be completed/worked towards in 1.11
