### ISSUE TITLE
1.8.9 TODO

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn#339]
- [ ] Support for direct liquid input in electrolyzer
- [ ] Fix Wrong Industrial Electrolyzer progress bar
- [x] Scrapboxinator
- [ ] Change Charge Bench to Charge-O-Mat
- [ ] Wrench Requirement config
- [x] Retrogen (1/2 done)
- [ ] Fix GUIS #279
- [x] Update AESU, IDSU, and LESU to fit the new GUI textures for them
- [ ] Transformers for new power net
- [ ] Fix: Energy storage units (AESU, IDSU, etc.) cannot be placed up or downwards
- [ ] Fix: Thermal Generator's isActive state
- [ ] Fix: Machines do not work well with automation (ie: extraction, insertion, etc.)

Textures:
- [ ] Pump Item
- [ ] Teleporter Item
- [x] Redo more ingot textures
- [x] IDSU GUI Redo (for some reason it is 32x)
- [x] Batbox
- [x] MFE
- [x] MFSU
- [x] LV Transformer 
- [x] MV Transformer 
- [x] HV Transformer 
- [ ] Bronze Armour
- [ ] Electric Fence
- [ ] Nuke
- [x] Grinder
- [ ] Redo lots of machine textures

**Comment by BBoldt** [comment]
I could help, yes, but you'll have to tell me exactly what you want made.

**Comment by modmuss50** [comment]
The thing is, I dont know :P Something different might be a good idea.

**Comment by gigabit101** [comment]
How about a giant hamster wheel and get a animal to run in it also @modmuss50 have fun rendering that ;)

**Comment by modmuss50** [comment]
Get me a model and yes I will do it

**Comment by modmuss50** [comment]
Add recipe crossover thing to find missing items.
Macerator(Grinder?)
Compressor
Circuits
Machine Block
Rubber Trees, and rubber
Coal Burning
Move powerapi into RebornCore, allows for solar panel mod

**Comment by modmuss50** [comment]
Full missing items list: https://gist.github.com/modmuss50/0a685e90db6770868947

**Comment by NinjaKap** [comment]
Power Gen Options? Well, UU-Matter. Make a "UU-Matter Generator" which uses UU-Matter & Water to generate mass amounts of power. Could be a promising idea?

**Comment by modmuss50** [comment]
Thats not a bad idea :+1:

**Comment by covers1624** [comment]
If you need any help with the rendering of this Hamster wheel, give me a pong on TS after the weekend, The new WorldRender in 1.8.9 is a LOT different from 1.7.

**Comment by modmuss50** [comment]
@covers1624 I think we were joking :P

**Comment by TheDoctorSoda** [comment]
Sure

**Comment by TheDoctorSoda** [comment]
What will the machine sides look like?

**Comment by modmuss50** [comment]
This: https://github.com/TechReborn/TechReborn/blob/1.7.10/src/main/resources/assets/techreborn/textures/blocks/machine/machine_side.png

**Comment by covers1624** [comment]
@modmuss50 I wasn't. Throw any TE Rendering this way i know the WorldRenderer for 1.8.9.

**Comment by ProfessorProspector** [comment]
@modmuss50 Just wanted to let you know, this is me TheDoctorSoda. I've been meaning to do the rebranding under this new name for a while and finally decided to do it because my website domain is expiring soonish (still 100 days but I wanna get ready)

**Comment by BBoldt** [comment]
Someone needs to go through and test all the multiblocks, last time I tried them a couple weeks ago, I got a series of crashes. I didn't save them because I thought the 1.8.9 branch wasn't really worth using or going to be improved. You guys seem to be working on that now though.

**Comment by ProfessorProspector** [comment]
@modmuss50 For the machines, is there an on and off texture?

**Comment by gigabit101** [comment]
For the machines yes

**Comment by ProfessorProspector** [comment]
Do we still need grinder and extractor front textures? Is the grinder just a macerator?

**Comment by gigabit101** [comment]
@ProfessorProspector can we get a texture for a Iron hammer used to make plates early game

**Comment by gigabit101** [comment]
@ProfessorProspector also copper and tin blocks

**Comment by ProfessorProspector** [comment]
Now wait...wasn't refined iron used back in the versions were recreating?
And sure I'll make those after school.

**Comment by modmuss50** [comment]
That animation looks cool

**Comment by gigabit101** [comment]
In ic2 yes but Greg tech still used plates

**Comment by ProfessorProspector** [comment]
Ah that makes sense. And thanks

**Comment by ProfessorProspector** [comment]
Do we want to keep the iconic IC2 plate texture, or make one unique for TechReborn?

**Comment by gigabit101** [comment]
It's OK atm but can I get a gui texture for the Manuel so a book like
texture and a texture for the item as well

**Comment by ProfessorProspector** [comment]
For the GUI texture...like a vanilla book gui or something a bit...bigger?

**Comment by gigabit101** [comment]
Something like the botania book I think will be cool

**Comment by gigabit101** [comment]
The faster I can get the gui the better going to work on the rewrite today

**Comment by ProfessorProspector** [comment]
Hmm I won't be able to start it until I get home later today in like 6 hours

**Comment by gigabit101** [comment]
That's fine I have work to do anyways and other things I can do first

**Comment by modmuss50** [comment]
Gig, if yo could load the pages from file, it would be possible to download/update the pda separate to the mod. This would allow a website where people could post contributions. I can do the downloading stuff.

**Comment by modmuss50** [comment]
Even if you just read json files form the jar file.

**Comment by gigabit101** [comment]
It's not worth it atm but I do have a clearer idea of what I won't it to do
this time

**Comment by gigabit101** [comment]
Also modmuss can you get the cables in or just the cable item for the
moment fir recipe sacks

**Comment by modmuss50** [comment]
I'll add a cable item, and if fluxed red stone is in use the cable from that.

**Comment by gigabit101** [comment]
That works for now

**Comment by modmuss50** [comment]
@ProfessorProspector Got a texture list here:

Lava/Water cell(Item), base of other ones
pump(item) could be like a bike pump or something?
teleporter(Item)
advancedAlloy(Item)
lvTransformer(Item)
mvTransformer(Item)
hvTransformer(Item)

Solar panel(block)

**Comment by modmuss50** [comment]
@gigabit101 can I use your water turbine code? And I will add the windturbine without fancy rendering.

**Comment by gigabit101** [comment]
Sure

**Comment by modmuss50** [comment]
Items that need a recipe:
- [x] Grinder
- [x] Generator
- [ ] Compressor
- [x] Extractor
- [x] ElectricFurnace
- [ ] windMill
- [x] solarPanel
- [ ] waterMill
- [ ] miningDrill
- [ ] diamondDrill
- [x] pump
- [ ] teleporter
- [ ] advancedAlloy
- [ ] lvTransformer
- [ ] mvTransformer
- [ ] hvTransformer

And more I guess

**Comment by ProfessorProspector** [comment]
I'll get on that texture work in a bit. Also...what do you think about dynamic cells, like the bucket.

**Comment by modmuss50** [comment]
It's possible, I don't think we have fluids for every cell.

**Comment by ProfessorProspector** [comment]
hey @gigabit101 next time you're working on this could you move everything in the manuel down a few pixels? Need a tiny bit of extra room for the border :P

**Comment by gigabit101** [comment]
@ProfessorProspector done

**Comment by ProfessorProspector** [comment]
Aren't the transformers supposed to be blocks? Or are these different transformers?

**Comment by modmuss50** [comment]
Yes they are, but in RF transformers aren't needed, I've got an idea though. So hold off

**Comment by Prospector** [comment]
Is there any way to make the uninsulated cable shock sounds not stack? When you're touching two or three of them the sound is unbearable.

Also, why is BlockMachineBase in reborn core, and not techreborn?

**Comment by modmuss50** [comment]
Ive updated the list, and removed all of the completed things

**Comment by modmuss50** [comment]
Most of the textues in that list arent needed @ProfessorProspector

**Comment by Prospector** [comment]
Alright. If you wanna remove any go ahead. I just stared adding a bunch of IC2 things.

**Comment by Prospector** [comment]
Are the transformers going to be blocks again or what? If you have an idea for their function let me know and I can start on textures later today.

**Comment by modmuss50** [comment]
yeah, they are going to be blocks. They will work the same as they do in ic2

**Comment by Prospector** [comment]
Are we not going to do energy storage blocks? Like batbox, mfe, etc?

**Comment by modmuss50** [comment]
humm, its easy to do. We can

**Comment by Prospector** [comment]
After the mod is up to par of the old gregtech, is it coin to continue to expand the mod in the same style as if Greg didn't go crazy and still was working on the mod, or are we just leaving it completely as it was?

**Comment by modmuss50** [comment]
Once it's all done, I'm done with it. I will fix things and update to new mc. Other people can add new things. But I cannot work on the same thing for ever.
