### ISSUE TITLE
1.9 TODO

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn#379]
This is the list of things that will be changed in 1.9:
- [ ] Rewirte GUI system
- [ ] Rewirte power net to use capabillitys
- [ ] Make the powernet threaded
- [ ] Use new item handlers
- [ ] Rewrite API

**Comment by modmuss50** [comment]
I will reopen when 1.9 is a thing

**Comment by Prospector** [comment]
Totally didn't mean to close this. Must've accidentally hit the button when scrolling on mobile.
