### ISSUE TITLE
Post-Big (v1.0.0) Release TODO

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#386]
These can wait until after the big release. If we can squeeze them in, great, but don't prioritize these:

**1.8.9:**
- [ ] Induction furnace
- [ ] Fix: Energy storage units (AESU, IDSU, etc.) cannot be placed up or downwards
- [ ] Wrench Requirement config
- [ ] Change Charge Bench to Charge-O-Matt

**1.9.0:**
- [ ] Make the powernet threaded
- [ ] Rewrite API 

Also above 1.8 changes should also be merged to 1.9.

**Comment by Prospector** [comment]
Moved to TODO tracker
