### ISSUE TITLE
Pre-Big (v1.0.0) Release TODO

### ISSUE THREAD

**Issue by Prospector** [TechReborn/TechReborn#387]
**1.8.9:**
- [ ] Support for direct liquid input in electrolyzer
- [ ] Fix Wrong Industrial Electrolyzer progress bar
- [ ] Fix GUIS #279
- [x] Transformers for new power net
- [ ] Fix: Thermal Generator's isActive state
- [ ] Fix: Machines do not work well with automation (ie: extraction, insertion, etc.)
- [ ] No compressor recipe
- [ ] Electric furnace doesn't work when cables are attached to it. (Actually a lot of machines don't)
- [ ] Extractor has no progress bar
- [ ] Recycler JEI handler shows the scrapbox recipes for some reason

**1.9.0:**

After the 1.8 issues are fixed they should also be merged into 1.9.

**Textures:**
- [ ] Bronze Armour
- [ ] Electric Fence
- [ ] Nuke
- [ ] Redo lots of machine textures

**Comment by modmuss50** [comment]
I have moved all of these to youtrack

**Comment by Prospector** [comment]
Awesome. Heading to bed now
