### ISSUE TITLE
[1.10.2] Misc issues.

### ISSUE THREAD

**Issue by Claycorp** [TechReborn/TechReborn#969]
- [ ] Saplings placed in world are missing their texture. #943
- [ ] Heat generator is missing its textures. #952 
- [ ] Block of yellow Garnet is missing all of its textures.
- [ ] Block of red Garnet is missing all of its textures.
- [ ] Block of refined iron is missing all of its textures.
- [ ] Compressed Air Source (Does not seem to be finished and is missing textures) #952 
- [ ] Electrolyzed Water Source (Does not seem to be finished and is missing textures) #952 
- [ ] Sulfur Cell
- [ ] Sodium Sulfide Cell
- [ ] Compressed Air Cell 
- [ ] Electrolyzed Water Cell 
- [ ] Nitrodiesel Cell 
- [ ] Nitrocarbon Cell
- [ ] Carbon Fiber Cell
- [ ] Sulfuric Acid Cell
- [ ] Wolframium Cell
- [ ] Diesel Cell
- [ ] Carbon Cell
- [ ] [Diamond Grinding Head has batteryUltimate Oredic. ](https://github.com/TechReborn/TechReborn/blob/1831ff4dbcae0290b7b527c4b10a61be92626330/src/main/java/techreborn/init/OreDict.java#L71)
- [ ] Scrap has no JEI recipe.

All of this is with default settings that the mod creates on startup.
Tech Reborn: 2.1.4.172
Forge: 2221

**Comment by Prospector** [comment]
If things don't have a recipe, usually it's intentional

**Comment by Claycorp** [comment]
Well I figured if it doesn't have a WIP tag on it was finished as other items that are WIP have tags on them.

**Comment by modmuss50** [comment]
Closing this as most of them have their own issues.
